### ISSUE TITLE
# (Pound sign) in method name cause error

### ISSUE THREAD

**Issue by sthembi** [learn-co-curriculum/instance-methods-lab-ruby#2]
If I follow the lab exactly, to create an instance method '#sit' the '#' in the method name creates a ruby error.
If I remove the '#' signs from the method names, no ruby error is encountered and the tests pass.

**Comment by AnnJohn** [comment]
Hi @sthembi the # symbol is a Ruby convention for naming methods and we don't include it when we write our methods. We wrote a note on this in an earlier Readme on methods, but we'll work on making it more clear. Thanks!
