### ISSUE TITLE
Next lesson

### ISSUE THREAD

**Issue by MajSB** [learn-co-curriculum/instance-methods-lab-ruby#4]
Hi 
I've forked the lab in this lesson using "Learn open" and then "Learn Submit". But the update is not done properly to allow me to move to the next lesson and mark this lesson as completed. 

![screen shot 2015-11-30 at 11 39 44](https://cloud.githubusercontent.com/assets/15914860/11472995/1db91e12-9757-11e5-9e40-bbfc80950403.png)

**Comment by AnnJohn** [comment]
Hi @MajSB since this looks to be an engineering issue, please use the Report a Bug feature to let our engineering team know. Also, you can use the Ask a Question tool in Learn and someone will get back to you right away to help you out! Thanks.
